export type DrugCategory =
  | "Induction"
  | "Neuromuscular Blocker"
  | "Opioid"
  | "Vasopressor / Inotrope"
  | "Local Anesthetic"
  | "Reversal Agent"
  | "Antiemetic"
  | "Volatile Anesthetic"
  | "Benzodiazepine";

export type Drug = {
  slug: string;
  name: string;
  generic?: string;
  brands?: string[];
  category: DrugCategory;
  class: string;
  mechanism: string;
  indications: string[];
  adultDose: string;
  pediatricDose?: string;
  onset: string;
  duration: string;
  metabolism: string;
  contraindications: string[];
  sideEffects: string[];
  pearls: string[];
  monitoring?: string;
};

export const drugs: Drug[] = [
  // ---------- INDUCTION ----------
  {
    slug: "propofol",
    name: "Propofol",
    brands: ["Diprivan"],
    category: "Induction",
    class: "Alkylphenol",
    mechanism: "GABA-A receptor agonist; potentiates chloride conductance.",
    indications: ["Induction & maintenance of GA", "ICU sedation", "Procedural sedation"],
    adultDose: "Induction: 1.5–2.5 mg/kg IV. Maintenance: 100–200 mcg/kg/min. Sedation: 25–75 mcg/kg/min.",
    pediatricDose: "Induction: 2.5–3.5 mg/kg IV (higher than adults).",
    onset: "~30 seconds",
    duration: "5–10 min (single bolus)",
    metabolism: "Hepatic (glucuronidation); extrahepatic clearance present.",
    contraindications: ["Egg/soy allergy (relative)", "Severe hemodynamic instability"],
    sideEffects: [
      "Hypotension (dose-dependent)",
      "Apnea",
      "Pain on injection",
      "Hypertriglyceridemia (prolonged infusion)",
      "Propofol infusion syndrome (PRIS) — rare, with infusions >4 mg/kg/h >48 h",
    ],
    pearls: [
      "Reduce dose 25–50% in elderly / hypovolemic / sick patients.",
      "Add 20–40 mg lidocaine to syringe to reduce injection pain.",
      "Antiemetic at sub-hypnotic doses (10–20 mg).",
    ],
  },
  {
    slug: "etomidate",
    name: "Etomidate",
    brands: ["Amidate"],
    category: "Induction",
    class: "Imidazole",
    mechanism: "GABA-A modulator with minimal cardiovascular effects.",
    indications: ["Induction in hemodynamically unstable patients", "RSI"],
    adultDose: "0.2–0.3 mg/kg IV",
    pediatricDose: "0.2–0.3 mg/kg IV",
    onset: "30–60 seconds",
    duration: "5–10 min",
    metabolism: "Hepatic esterases & plasma esterases.",
    contraindications: ["Known adrenal insufficiency (relative)"],
    sideEffects: [
      "Myoclonus on induction",
      "Adrenal cortical suppression (even single dose, ~24 h)",
      "PONV (high incidence)",
      "Pain on injection",
    ],
    pearls: [
      "First-line induction for the hemodynamically tenuous patient.",
      "Single-dose adrenal suppression rarely clinically significant — but consider in septic shock.",
    ],
  },
  {
    slug: "ketamine",
    name: "Ketamine",
    brands: ["Ketalar"],
    category: "Induction",
    class: "Phencyclidine derivative (NMDA antagonist)",
    mechanism: "Non-competitive NMDA receptor antagonist; produces dissociative anesthesia.",
    indications: [
      "Induction (esp. shock, severe asthma)",
      "Analgesia",
      "Pediatric sedation",
      "Bronchospasm",
    ],
    adultDose: "Induction: 1–2 mg/kg IV or 4–6 mg/kg IM. Analgesia: 0.1–0.5 mg/kg IV.",
    pediatricDose: "Induction: 1–2 mg/kg IV or 4–6 mg/kg IM. Sedation: 0.5–1 mg/kg IV.",
    onset: "30–60 sec IV; 3–5 min IM",
    duration: "10–20 min (IV)",
    metabolism: "Hepatic CYP450 to norketamine (active).",
    contraindications: [
      "Uncontrolled HTN",
      "Severe coronary disease (relative)",
      "Increased ICP (controversial — modern data more permissive)",
      "Active psychosis",
    ],
    sideEffects: [
      "Hypertension, tachycardia",
      "Emergence delirium (mitigate with benzo)",
      "Hypersalivation",
      "Increased IOP",
    ],
    pearls: [
      "Preserves respiratory drive & airway reflexes.",
      "Bronchodilator — first choice for severe asthma induction.",
      "Co-administer midazolam or low-dose propofol to blunt emergence reactions.",
    ],
  },
  {
    slug: "midazolam",
    name: "Midazolam",
    brands: ["Versed"],
    category: "Benzodiazepine",
    class: "Imidazo-benzodiazepine",
    mechanism: "GABA-A potentiation via benzodiazepine binding site.",
    indications: ["Premedication", "Procedural sedation", "Status epilepticus", "Induction adjunct"],
    adultDose: "Premed: 1–2 mg IV. Induction adjunct: 0.05–0.15 mg/kg.",
    pediatricDose: "PO premed: 0.5 mg/kg (max 20 mg). IV: 0.05–0.1 mg/kg.",
    onset: "1–3 min IV; 15 min PO",
    duration: "30–60 min",
    metabolism: "Hepatic CYP3A4 (active metabolite α-hydroxymidazolam).",
    contraindications: ["Acute narrow-angle glaucoma", "Hypersensitivity"],
    sideEffects: ["Respiratory depression (synergistic with opioids)", "Hypotension", "Paradoxical agitation in elderly/children"],
    pearls: [
      "Reverse with flumazenil 0.2 mg IV q1 min (max 1 mg) — caution in chronic users.",
      "Powerful anterograde amnesia even at low doses.",
    ],
  },
  {
    slug: "dexmedetomidine",
    name: "Dexmedetomidine",
    brands: ["Precedex"],
    category: "Induction",
    class: "Alpha-2 agonist (centrally selective)",
    mechanism: "Highly selective α2-adrenoceptor agonist — sedation, analgesia, sympatholysis.",
    indications: ["ICU sedation", "Procedural sedation", "Awake fiberoptic intubation", "PONV adjunct"],
    adultDose: "Load: 1 mcg/kg over 10 min (often omitted). Infusion: 0.2–0.7 mcg/kg/h.",
    pediatricDose: "0.5–1 mcg/kg load, infusion 0.2–1 mcg/kg/h.",
    onset: "5–10 min",
    duration: "60–120 min after infusion stop",
    metabolism: "Hepatic; conjugation & CYP2A6.",
    contraindications: ["Advanced heart block (without pacemaker)"],
    sideEffects: ["Bradycardia", "Hypotension (or transient HTN with bolus)", "Dry mouth"],
    pearls: [
      "Sedation that preserves respiratory drive — ideal for awake intubation.",
      "Skip the load in elderly / cardiac patients to avoid hemodynamic swings.",
    ],
  },
  // ---------- PARALYTICS ----------
  {
    slug: "succinylcholine",
    name: "Succinylcholine",
    brands: ["Anectine", "Quelicin"],
    category: "Neuromuscular Blocker",
    class: "Depolarizing NMBA",
    mechanism: "ACh receptor agonist → sustained depolarization → flaccid paralysis.",
    indications: ["Rapid sequence intubation", "Laryngospasm", "Brief paralysis"],
    adultDose: "1–1.5 mg/kg IV (defasciculate first with non-depolarizer if desired). IM: 3–4 mg/kg.",
    pediatricDose: "IV: 2 mg/kg (infants); 1–1.5 mg/kg (children). IM: 4 mg/kg.",
    onset: "30–60 sec",
    duration: "5–10 min",
    metabolism: "Plasma pseudocholinesterase (butyrylcholinesterase).",
    contraindications: [
      "History or family hx of malignant hyperthermia",
      "Hyperkalemia (K+ rises ~0.5 mEq/L; up to 5–10 mEq/L in susceptible)",
      "Major burns >24–48 h old",
      "Denervation injury / prolonged immobility",
      "Muscular dystrophy (Duchenne)",
      "Pseudocholinesterase deficiency",
    ],
    sideEffects: [
      "Fasciculations & myalgia",
      "Hyperkalemia",
      "Bradycardia (esp. peds, repeat dosing)",
      "Increased intragastric / IOP / ICP",
      "MH trigger",
    ],
    pearls: [
      "Pretreat peds with atropine 0.02 mg/kg to prevent bradycardia.",
      "Prolonged block (>1 h) → suspect pseudocholinesterase deficiency.",
    ],
  },
  {
    slug: "rocuronium",
    name: "Rocuronium",
    brands: ["Zemuron"],
    category: "Neuromuscular Blocker",
    class: "Aminosteroid non-depolarizing NMBA",
    mechanism: "Competitive ACh receptor antagonist at neuromuscular junction.",
    indications: ["Tracheal intubation", "Intraoperative paralysis", "RSI alternative"],
    adultDose: "Intubation: 0.6 mg/kg (RSI 1.0–1.2 mg/kg). Maintenance: 0.1–0.2 mg/kg.",
    pediatricDose: "0.6–1.2 mg/kg IV.",
    onset: "60–90 sec (RSI dose) / 2–3 min (standard)",
    duration: "30–60 min (longer with high dose)",
    metabolism: "Primarily hepatic (biliary excretion).",
    contraindications: ["Hypersensitivity"],
    sideEffects: ["Mild tachycardia (vagolytic)", "Anaphylaxis (most common NMBA trigger)"],
    pearls: [
      "RSI alternative to sux when sux is contraindicated — pair with sugammadex availability.",
      "Sugammadex 16 mg/kg reverses even profound block.",
    ],
  },
  {
    slug: "vecuronium",
    name: "Vecuronium",
    brands: ["Norcuron"],
    category: "Neuromuscular Blocker",
    class: "Aminosteroid non-depolarizing NMBA",
    mechanism: "Competitive nicotinic ACh receptor antagonist.",
    indications: ["Intubation", "Intraoperative paralysis"],
    adultDose: "Intubation: 0.08–0.1 mg/kg. Maintenance: 0.01–0.015 mg/kg.",
    pediatricDose: "0.1 mg/kg.",
    onset: "3–5 min",
    duration: "25–40 min",
    metabolism: "Hepatic; biliary & renal excretion. Active metabolite 3-OH-vecuronium.",
    contraindications: ["Hypersensitivity"],
    sideEffects: ["Prolonged block in hepatic/renal failure", "Minimal CV effects"],
    pearls: ["Hemodynamically neutral — useful in cardiac cases.", "Reversible with sugammadex."],
  },
  {
    slug: "cisatracurium",
    name: "Cisatracurium",
    brands: ["Nimbex"],
    category: "Neuromuscular Blocker",
    class: "Benzylisoquinolinium non-depolarizing NMBA",
    mechanism: "Competitive nicotinic ACh antagonist.",
    indications: ["Intubation", "Maintenance, esp. in hepatic/renal failure", "ICU paralysis (ARDS)"],
    adultDose: "Intubation: 0.15–0.2 mg/kg. Infusion: 1–3 mcg/kg/min.",
    pediatricDose: "0.1–0.15 mg/kg.",
    onset: "2–3 min",
    duration: "30–60 min",
    metabolism: "Hofmann elimination (organ-independent) → laudanosine.",
    contraindications: ["Hypersensitivity"],
    sideEffects: ["Rare histamine release", "Laudanosine accumulation theoretical (high-dose ICU)"],
    pearls: [
      "Drug of choice when organ failure precludes hepatic / renal clearance.",
      "NOT reversed by sugammadex (benzylisoquinolinium).",
    ],
  },
  // ---------- OPIOIDS ----------
  {
    slug: "fentanyl",
    name: "Fentanyl",
    brands: ["Sublimaze"],
    category: "Opioid",
    class: "Synthetic phenylpiperidine μ-agonist",
    mechanism: "μ-opioid receptor agonist; 75–125× more potent than morphine.",
    indications: ["Intraoperative analgesia", "Sedation", "Pain control"],
    adultDose: "Induction adjunct: 1–3 mcg/kg. Maintenance: 0.5–2 mcg/kg PRN. Cardiac dose: 5–20 mcg/kg.",
    pediatricDose: "1–2 mcg/kg.",
    onset: "1–2 min",
    duration: "30–60 min (single dose); context-sensitive half-time grows with infusion.",
    metabolism: "Hepatic CYP3A4.",
    contraindications: ["MAOI use (relative)", "Severe respiratory depression"],
    sideEffects: ["Respiratory depression", "Bradycardia", "Chest wall rigidity (high doses/fast push)", "Pruritus"],
    pearls: [
      "Rigidity from rapid bolus → ventilation impossible; treat with NMBA + naloxone.",
      "Short single-dose action belies long context-sensitive half-time on infusion.",
    ],
  },
  {
    slug: "remifentanil",
    name: "Remifentanil",
    brands: ["Ultiva"],
    category: "Opioid",
    class: "Ultra-short acting μ-agonist (ester linkage)",
    mechanism: "μ-opioid agonist; metabolized by non-specific plasma esterases.",
    indications: ["TIVA", "Brief intense analgesia", "Awake intubation"],
    adultDose: "Bolus 0.5–1 mcg/kg. Infusion: 0.05–0.5 mcg/kg/min (TIVA up to 1).",
    pediatricDose: "0.05–0.3 mcg/kg/min.",
    onset: "1–2 min",
    duration: "3–10 min regardless of infusion duration",
    metabolism: "Plasma & tissue esterases (organ-independent).",
    contraindications: ["Epidural/intrathecal use (glycine vehicle)"],
    sideEffects: ["Profound bradycardia/hypotension", "Chest wall rigidity", "Hyperalgesia after long infusion"],
    pearls: [
      "Always have a longer-acting analgesic on board before stopping the infusion.",
      "Useful in obese, hepatic/renal failure — context-insensitive.",
    ],
  },
  {
    slug: "sufentanil",
    name: "Sufentanil",
    brands: ["Sufenta"],
    category: "Opioid",
    class: "μ-agonist",
    mechanism: "μ-opioid receptor agonist; 5–10× more potent than fentanyl.",
    indications: ["Cardiac anesthesia", "Neuraxial analgesia"],
    adultDose: "0.1–0.5 mcg/kg IV; epidural: 10–20 mcg.",
    onset: "1–3 min",
    duration: "30–60 min",
    metabolism: "Hepatic CYP3A4.",
    contraindications: ["Severe respiratory depression"],
    sideEffects: ["Respiratory depression", "Bradycardia", "Chest wall rigidity"],
    pearls: ["High-dose cardiac induction provides exceptional hemodynamic stability."],
  },
  {
    slug: "morphine",
    name: "Morphine",
    category: "Opioid",
    class: "Natural μ-agonist",
    mechanism: "μ-opioid receptor agonist.",
    indications: ["Post-op pain", "Neuraxial analgesia (Duramorph)"],
    adultDose: "IV: 2–4 mg q4h PRN. Neuraxial: intrathecal 100–300 mcg; epidural 2–5 mg.",
    pediatricDose: "0.05–0.1 mg/kg IV.",
    onset: "5–10 min IV",
    duration: "3–4 h IV; up to 24 h intrathecal",
    metabolism: "Hepatic glucuronidation → M6G (active, renally cleared).",
    contraindications: ["Renal failure (caution — M6G accumulates)"],
    sideEffects: ["Histamine release / hypotension", "Pruritus", "PONV", "Constipation", "Delayed respiratory depression with neuraxial"],
    pearls: ["Monitor 24 h for delayed respiratory depression after intrathecal morphine."],
  },
  {
    slug: "hydromorphone",
    name: "Hydromorphone",
    brands: ["Dilaudid"],
    category: "Opioid",
    class: "Semisynthetic μ-agonist",
    mechanism: "μ-opioid receptor agonist; ~5–7× more potent than morphine.",
    indications: ["Acute & chronic pain", "PCA"],
    adultDose: "IV: 0.2–0.5 mg q3–4 h. PCA demand: 0.1–0.3 mg q6–10 min.",
    onset: "5–10 min IV",
    duration: "3–4 h",
    metabolism: "Hepatic glucuronidation.",
    contraindications: ["Severe respiratory depression"],
    sideEffects: ["Sedation", "Respiratory depression", "Pruritus"],
    pearls: ["Preferred over morphine in renal failure (no clinically active metabolite)."],
  },
  // ---------- VASOPRESSORS ----------
  {
    slug: "phenylephrine",
    name: "Phenylephrine",
    category: "Vasopressor / Inotrope",
    class: "Pure α1 agonist",
    mechanism: "Selective α1 vasoconstriction; reflex bradycardia possible.",
    indications: ["Hypotension (esp. spinal anesthesia, vasodilatory shock with tachycardia)"],
    adultDose: "Bolus 50–200 mcg IV. Infusion: 20–200 mcg/min (or 0.15–0.75 mcg/kg/min).",
    pediatricDose: "Bolus 1–5 mcg/kg.",
    onset: "<1 min",
    duration: "5–20 min (bolus)",
    metabolism: "MAO; hepatic.",
    contraindications: ["Severe HTN", "Closed-angle glaucoma"],
    sideEffects: ["Reflex bradycardia", "Decreased CO in cardiac dysfunction"],
    pearls: [
      "First-line for spinal-induced hypotension at C-section.",
      "Avoid in low-output states — pure afterload increase can drop CO.",
    ],
  },
  {
    slug: "ephedrine",
    name: "Ephedrine",
    category: "Vasopressor / Inotrope",
    class: "Mixed direct/indirect α and β agonist",
    mechanism: "Releases endogenous NE; direct α and β effects.",
    indications: ["Hypotension with bradycardia"],
    adultDose: "5–10 mg IV bolus q3–5 min (max ~50 mg).",
    pediatricDose: "0.1–0.3 mg/kg IV.",
    onset: "1 min",
    duration: "10–60 min",
    metabolism: "Mostly excreted unchanged in urine.",
    contraindications: ["Severe CAD", "MAOI use"],
    sideEffects: ["Tachycardia", "Tachyphylaxis", "HTN"],
    pearls: ["Useful when both pressure and rate are low; less first-line at C-section due to fetal acidosis (vs phenylephrine)."],
  },
  {
    slug: "norepinephrine",
    name: "Norepinephrine",
    brands: ["Levophed"],
    category: "Vasopressor / Inotrope",
    class: "Potent α + modest β1 agonist",
    mechanism: "α1 vasoconstriction with mild β1 inotropy.",
    indications: ["Septic shock (first-line)", "Vasodilatory shock"],
    adultDose: "Infusion 0.02–1 mcg/kg/min (titrate).",
    pediatricDose: "0.05–0.5 mcg/kg/min.",
    onset: "<1 min",
    duration: "1–2 min",
    metabolism: "MAO/COMT.",
    contraindications: ["Mesenteric/peripheral vascular thrombosis (relative)"],
    sideEffects: ["Arrhythmia", "Peripheral ischemia/extravasation injury (treat with phentolamine)"],
    pearls: ["Now safely run via large-bore peripheral IV at low concentrations short-term (consensus shift)."],
  },
  {
    slug: "epinephrine",
    name: "Epinephrine",
    category: "Vasopressor / Inotrope",
    class: "α and β agonist (dose-dependent)",
    mechanism: "Low dose: β-predominant (inotropy, vasodilation). High dose: α-predominant.",
    indications: ["Cardiac arrest", "Anaphylaxis", "Severe bronchospasm", "Cardiogenic shock"],
    adultDose: "Arrest: 1 mg IV/IO q3–5 min. Anaphylaxis: 0.3–0.5 mg IM q5–15 min. Infusion: 0.02–0.2 mcg/kg/min.",
    pediatricDose: "Arrest: 0.01 mg/kg (1:10,000) IV/IO. Anaphylaxis: 0.01 mg/kg IM (max 0.3 mg).",
    onset: "<1 min IV",
    duration: "5–10 min",
    metabolism: "MAO/COMT.",
    contraindications: ["None in life-threatening situations"],
    sideEffects: ["Tachyarrhythmia", "Hyperglycemia", "Lactic acidosis"],
    pearls: ["IM lateral thigh is fastest extra-vascular route in anaphylaxis."],
  },
  {
    slug: "vasopressin",
    name: "Vasopressin",
    category: "Vasopressor / Inotrope",
    class: "ADH analog (V1 vasoconstrictor)",
    mechanism: "V1 receptor agonism → vasoconstriction independent of adrenergic system.",
    indications: ["Septic shock adjunct", "Vasoplegia (post-CPB)", "Cardiac arrest (deprecated in ACLS)"],
    adultDose: "Infusion 0.01–0.04 U/min (fixed).",
    onset: "1–3 min",
    duration: "10–20 min",
    metabolism: "Hepatic & renal.",
    contraindications: ["Coronary ischemia (high dose)"],
    sideEffects: ["Splanchnic ischemia", "Hyponatremia"],
    pearls: ["Catecholamine-sparing — useful when escalating norepinephrine doses cause tachyarrhythmia."],
  },
  // ---------- LOCAL ANESTHETICS ----------
  {
    slug: "lidocaine",
    name: "Lidocaine",
    brands: ["Xylocaine"],
    category: "Local Anesthetic",
    class: "Amide local anesthetic",
    mechanism: "Blocks voltage-gated Na+ channels.",
    indications: ["Local/regional anesthesia", "IV antiarrhythmic", "Attenuate intubation response"],
    adultDose: "Max: 4.5 mg/kg plain; 7 mg/kg with epi. IV: 1–1.5 mg/kg before intubation.",
    pediatricDose: "Max 4.5 mg/kg plain.",
    onset: "Rapid (1–5 min infiltration)",
    duration: "1–2 h (4 h with epi)",
    metabolism: "Hepatic (CYP3A4/1A2).",
    contraindications: ["Amide allergy", "3rd-degree heart block (IV)"],
    sideEffects: ["LAST (perioral numbness → seizures → CV collapse)", "Methemoglobinemia (high dose)"],
    pearls: [
      "Always know your max dose and the patient's weight.",
      "LAST treatment: lipid emulsion 1.5 mL/kg bolus → 0.25 mL/kg/min.",
    ],
  },
  {
    slug: "bupivacaine",
    name: "Bupivacaine",
    brands: ["Marcaine", "Sensorcaine"],
    category: "Local Anesthetic",
    class: "Long-acting amide LA",
    mechanism: "Blocks voltage-gated Na+ channels with high cardiac affinity.",
    indications: ["Regional blocks", "Epidural/spinal", "Post-op wound infiltration"],
    adultDose: "Max: 2 mg/kg plain (175 mg); 3 mg/kg with epi (225 mg). Spinal: 7.5–15 mg.",
    onset: "5–10 min (infiltration); 5–8 min (epidural)",
    duration: "4–8 h",
    metabolism: "Hepatic.",
    contraindications: ["IV regional (Bier block) — high cardiotoxicity"],
    sideEffects: ["Profound cardiotoxicity (refractory VF) — treat with lipid emulsion", "LAST"],
    pearls: [
      "More cardiotoxic than equipotent lidocaine — the 'CC/CNS ratio' is lower.",
      "Levobupivacaine and ropivacaine are less cardiotoxic alternatives.",
    ],
  },
  {
    slug: "ropivacaine",
    name: "Ropivacaine",
    brands: ["Naropin"],
    category: "Local Anesthetic",
    class: "Long-acting amide LA (S-enantiomer)",
    mechanism: "Na+ channel blockade; preferential sensory > motor block.",
    indications: ["Peripheral nerve blocks", "Epidural labor analgesia"],
    adultDose: "Max: 3 mg/kg. Epidural 0.1–0.2% infusion 6–14 mL/h.",
    onset: "10–20 min",
    duration: "3–6 h",
    metabolism: "Hepatic CYP1A2.",
    contraindications: ["IV regional"],
    sideEffects: ["LAST (less cardiotoxic than bupivacaine)"],
    pearls: ["Excellent labor epidural agent — analgesia with preserved motor function."],
  },
  // ---------- REVERSAL ----------
  {
    slug: "sugammadex",
    name: "Sugammadex",
    brands: ["Bridion"],
    category: "Reversal Agent",
    class: "γ-cyclodextrin encapsulator",
    mechanism: "Encapsulates rocuronium/vecuronium 1:1, removing them from NMJ.",
    indications: ["Reversal of rocuronium/vecuronium NMB"],
    adultDose: "Routine: 2 mg/kg (TOF ≥2). Deep: 4 mg/kg (PTC 1–2). Immediate: 16 mg/kg.",
    pediatricDose: "Same dosing as adults.",
    onset: "1–3 min",
    duration: "Pharmacologic effect ~24 h",
    metabolism: "Renal excretion (unchanged).",
    contraindications: ["Severe renal impairment (CrCl <30 — caution)"],
    sideEffects: [
      "Bradycardia (rare but possible cardiac arrest reported)",
      "Hypersensitivity / anaphylaxis (~0.3%)",
      "Reduced efficacy of hormonal contraceptives (counsel × 7 days)",
    ],
    pearls: [
      "16 mg/kg can rescue 'cannot intubate, cannot ventilate' after high-dose rocuronium RSI.",
      "Wait 5 min before redosing rocuronium after 2–4 mg/kg; 24 h after 16 mg/kg.",
    ],
  },
  {
    slug: "neostigmine",
    name: "Neostigmine",
    category: "Reversal Agent",
    class: "Acetylcholinesterase inhibitor",
    mechanism: "Inhibits AChE → ↑ACh at NMJ; outcompetes non-depolarizers.",
    indications: ["Reversal of non-depolarizing NMB (TOF ≥2)"],
    adultDose: "0.04–0.07 mg/kg IV (max ~5 mg). Co-administer glycopyrrolate 0.2 mg per 1 mg neostigmine.",
    pediatricDose: "0.04 mg/kg IV.",
    onset: "5–10 min",
    duration: "60 min",
    metabolism: "Hepatic / plasma esterases; renal excretion (50%).",
    contraindications: ["Mechanical bowel/urinary obstruction", "Deep blockade (TOF count 0)"],
    sideEffects: ["Bradycardia", "Bronchospasm", "Increased secretions", "PONV"],
    pearls: [
      "Ceiling effect — cannot reverse deep block; use sugammadex if available.",
      "Always pair with anti-muscarinic (glycopyrrolate or atropine).",
    ],
  },
  {
    slug: "naloxone",
    name: "Naloxone",
    brands: ["Narcan"],
    category: "Reversal Agent",
    class: "Pure opioid antagonist",
    mechanism: "Competitive μ-opioid receptor antagonist.",
    indications: ["Opioid overdose / oversedation", "Opioid-induced pruritus (low dose)"],
    adultDose: "Reversal: 0.04–0.4 mg IV q2–3 min. Overdose: 0.4–2 mg IV/IM/IN.",
    pediatricDose: "0.01 mg/kg IV (up to 0.1 mg/kg).",
    onset: "1–2 min",
    duration: "30–60 min (less than most opioids — re-narcotization risk)",
    metabolism: "Hepatic glucuronidation.",
    contraindications: ["Known hypersensitivity"],
    sideEffects: ["Acute withdrawal", "Pulmonary edema (rare)", "Pain crisis"],
    pearls: [
      "Titrate in 0.04 mg increments to restore respiration without abolishing analgesia.",
      "Re-dose anticipated — duration is shorter than most opioids.",
    ],
  },
  // ---------- ANTIEMETICS ----------
  {
    slug: "ondansetron",
    name: "Ondansetron",
    brands: ["Zofran"],
    category: "Antiemetic",
    class: "5-HT3 receptor antagonist",
    mechanism: "Blocks 5-HT3 receptors in CTZ and vagal afferents.",
    indications: ["PONV prevention/treatment", "Chemotherapy-induced nausea"],
    adultDose: "4 mg IV at end of case (prophylaxis); 4 mg IV q4–8 h (rescue).",
    pediatricDose: "0.1 mg/kg IV (max 4 mg).",
    onset: "5–15 min",
    duration: "4–8 h",
    metabolism: "Hepatic CYP3A4.",
    contraindications: ["Long QT syndrome (relative; dose-dependent QT prolongation)"],
    sideEffects: ["Headache", "Constipation", "QT prolongation"],
    pearls: ["Most effective if given at end of case rather than at induction."],
  },
  {
    slug: "dexamethasone",
    name: "Dexamethasone",
    brands: ["Decadron"],
    category: "Antiemetic",
    class: "Synthetic glucocorticoid",
    mechanism: "Unclear antiemetic mechanism; anti-inflammatory.",
    indications: ["PONV prophylaxis", "Airway edema", "Adjunct analgesia"],
    adultDose: "PONV: 4–8 mg IV at induction.",
    pediatricDose: "0.15 mg/kg IV (max 8 mg).",
    onset: "Hours (analgesic effect ~1 h)",
    duration: "24+ h",
    metabolism: "Hepatic.",
    contraindications: ["Systemic fungal infection"],
    sideEffects: ["Transient hyperglycemia", "Perineal burning on rapid push"],
    pearls: ["Synergistic with ondansetron — combine for high-risk PONV patients."],
  },
];

export const drugCategories: DrugCategory[] = [
  "Induction",
  "Neuromuscular Blocker",
  "Opioid",
  "Vasopressor / Inotrope",
  "Local Anesthetic",
  "Reversal Agent",
  "Antiemetic",
  "Volatile Anesthetic",
  "Benzodiazepine",
];

export function getDrug(slug: string) {
  return drugs.find((d) => d.slug === slug);
}
